// JavaScript Document
/* eslint-env es6 */

// This block injects custom CSS into the ArgoNet form.
function addCSS() {
	const uriAddressCSS = '//www.rutgersprep.org/uploaded/Tech_Office/ArgoNet_Stylesheets/event_registration/new_form/hsStyle.css?';
	const timeNow = Date.now();
	const finalAddress = uriAddressCSS + timeNow;

	// construct the link
	const hubLinkCSS = document.createElement('link');
	hubLinkCSS.defer = true;
	hubLinkCSS.rel = 'stylesheet';
	hubLinkCSS.type = 'text/css';
	hubLinkCSS.href = finalAddress;
	hubLinkCSS.id = 'rpsCSS';

	document.getElementsByTagName('head')[0].appendChild(hubLinkCSS);
}

// This block injects the code in postToHS.js into the ArgoNet form.
function addLinkJS() {
	const uriAddressLinkJS = '//www.rutgersprep.org/uploaded/Tech_Office/ArgoNet_Stylesheets/event_registration/new_form/postToHS.js?';
	const timeNow = Date.now();
	const finalAddress = uriAddressLinkJS + timeNow;

	const hubLinkScript = document.createElement('script');
	hubLinkScript.defer = true;
	hubLinkScript.type = 'text/javascript';
	hubLinkScript.src = finalAddress;
	hubLinkScript.id = 'rpsJS';

	document.getElementsByTagName('head')[0].appendChild(hubLinkScript);
}

// This block adds a custom submit button.  We need this so that we can trigger the submission scripts for Hubspot before we submit the ArgoNet form.
function addSubmitButton(hubID) {
	// $('#form-formbuttons button.btn-approve.submitreview:not(#rpsSubmitButton)').css('display'); // hide the button generated by the form.

	const newSubmitButton = document.createElement('button');
	newSubmitButton.id = 'rpsSubmitButton';
	newSubmitButton.className = 'btn btn-approve active btn-sm pull-left'; // these are the classes that already existed in blackbaud's code.

	// attach function to submit everything.
	newSubmitButton.addEventListener('click', () => {
		submitData(hubID);
	});

	// label the button
	const textnode = document.createTextNode('Accept');
	newSubmitButton.appendChild(textnode);

	$('#form-formbuttons').prepend(newSubmitButton); // add button to correct div.
}

if ($('#rpsJS').length < 1) {
	addLinkJS(); // inject the Hubspot Link code JS file.
}

if ($('#rpsCSS').length < 1) {
	addCSS(); // inject the CSS file.
}

// This is how you trigger anything that isn't tied to an event listener.  This gets run every time a new tab is selected, so we can run functions from here to get them to happen on the page as it is used.
function reTrigger() {
	// add code here if desired.
}

// This only runs on the 'Review' page and, mostly, is used to add all of the logic for the hubspot submission.
function reViewTrigger() {
	// check to make sure we are on the correct page.
	if ($('#rpsSubmitButton').length < 1 && $('li.tab.active > a').text().trim() === 'Review') {
		waitForVariable('hubCodeReady', () => {
			addSubmitButton(hubCodeReady); // inject new submit button.
		});
	} else {
		console.log('not Review page');
	}
}
